### ISSUE TITLE
java.lang.IllegalStateException: Image is already closed

### ISSUE THREAD

**Issue by digvijayLogistic** [xulihang/cordova-plugin-dynamsoft-barcode-reader#2]
Fatal Exception: java.lang.IllegalStateException: Image is already closed
       at android.media.Image.throwISEIfImageIsInvalid(Image.java:72)
       at android.media.ImageReader$SurfaceImage.getPlanes(ImageReader.java:895)
       at com.dynamsoft.dce.CameraEnhancer$10.onImageAvailable(CameraEnhancer.java:1524)
       at android.media.ImageReader$ListenerHandler.handleMessage(ImageReader.java:798)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:241)
       at android.os.HandlerThread.run(HandlerThread.java:67)
       
    We are getting this crash on firebase crashlytics, Can you please help me to resolve this issue ??

**Comment by xulihang** [comment]
I am not having this problem using this demo: <https://github.com/tony-xlh/Ionic-Angular-Cordova-Barcode-Scanner>.

Could you provide a demo which can reproduce this error?

**Comment by digvijayLogistic** [comment]
I have added this plugin on my current project and there is on firebase crashalytics this crash is shown.

**Comment by xulihang** [comment]
Do you call the destroy method? This may cause this error.

Please contact [support@dynamsoft.com](mailto:support@dynamsoft.com) for support.

**Comment by digvijayLogistic** [comment]
We are not call destroy method at all.
